remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: true
  volunteer: false

date:
  all time: false
  month: false
  week: false
  24 hours: true

searches:
  - location: 'Worldwide'
    positions:
      - 'Health'
      - 'Medical'
      - 'Medicine'
      - 'Healthcare'
      - 'Physician'
      - 'Paralegal'
      - 'HealthTech'

  # - location: 'United States'
  #   positions:
  #     - 'Injury'
  #     - 'Witness'
  
  # - location: 'Germany'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Japan'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'India'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'United Kingdom'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'France'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Italy'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Canada'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Brazil'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
   
  # - location: 'South Korea'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'

  
  # - location: 'Mexico'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Australia'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Spain'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Indonesia'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'

  # - location: 'Turkey'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Netherlands'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Saudi Arabia'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Switzerland'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Taiwan'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Belgium'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Sweden'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Argentina'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Ireland'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'United Arab Emirates'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Austria'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Singapore'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Israel'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Norway'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'

  # - location: 'Qatar'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Denmark'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Hong Kong'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  
  # - location: 'Portugal'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'

  
  # - location: 'Chile'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'New Zealand'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'

  # - location: 'Iceland'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Finland'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'
  
  # - location: 'Liechtenstein'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'

  # - location: 'Luxembourg'
  #   positions:
  #     - 'Health'
  #     - 'Medical'
  #     - 'Medicine'
  #     - 'Healthcare'
  #     - 'Physician'

apply_once_at_company: false 

distance: 100

company_blacklist:
  - wayfair
  - Crossover
  - Jobot
  - Jobot Consulting
  - Jobot Health
  - TORKLAW
  - Mindrift
  - Impact HealthCare
  - AO Globe Life
  - Tubre Family Financial

title_blacklist:
  - Attorney
  - Attorneys
  - Board-Certified
  - Certified
  - Coder
  - Dental
  - Dentist
  - Dentists
  - Dentistry
  - Insurance
  - Lawyers
  - Lawyer
  - Licensed
  - Maxillofacial
  - Nurse
  - Nurses
  - Oral
  - Orthodontic
  - Orthodontics
  - Orthodontist
  - Orthodontists
  - Radiologic
  - Radiologist
  - Radiologists
  - Radiology
  - Registered
  - Therapist
  - Therapists
  - Sales
  - Telesales
  - Sales-

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'

resume_style: "Modern Grey"