remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: true
  volunteer: false

date:
  all time: false
  month: false
  week: false
  24 hours: true

searches:
  - location: "Worldwide"
    positions:
      - "Health"
      - "Medical"
      - "Medicine"
      - "Healthcare"
      - "Physician"
      - "Paralegal"
      - "HealthTech"

apply_once_at_company: false

distance: 100

company_blacklist:
  - wayfair
  - Crossover
  - Jobot
  - Jobot Consulting
  - Jobot Health
  - TORKLAW
  - Mindrift
  - Impact HealthCare
  - AO Globe Life
  - Globe Life AO
  - Tubre Family Financial

title_blacklist:
  - Attorney
  - Attorneys
  - Board-Certified
  - Certified
  - Coder
  - Dental
  - Dentist
  - Dentists
  - Dentistry
  - Insurance
  - Lawyers
  - Lawyer
  - Licensed
  - Maxillofacial
  - Nurse
  - Nurses
  - Oral
  - Orthodontic
  - Orthodontics
  - Orthodontist
  - Orthodontists
  - Radiologic
  - Radiologist
  - Radiologists
  - Radiology
  - Registered
  - Therapist
  - Therapists
  - Sales
  - Telesales
  - Tourism
  - Sales
  - No Experience
  - Salesperson
  - Investor

description_blacklist:
  # Add keywords or phrases here that should cause a job to be skipped if found in the description.
  # Examples:
  # - "requires 5+ years experience"
  # - "on-site"
  # - "relocation assistance not provided"
  - Tourism
  - Sales Representative

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: gemini
llm_model: "gemini-2.5-flash-preview-04-17"

resume_style: "Modern Grey"
